#app.yaml
runtime: python310

env_variables:
  CLOUD_SQL_USERNAME: caps
  CLOUD_SQL_PASSWORD: 123456
  CLOUD_SQL_DATABASE_NAME: capfits
  CLOUD_SQL_CONNECTION_NAME: capfits-c22-ps041:asia-southeast2:db-capfits
