"""adding all tables

Revision ID: 3a93cf47e19a
Revises: a0cf862ced33
Create Date: 2022-06-03 20:16:35.233516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a93cf47e19a'
down_revision = 'a0cf862ced33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_type',
    sa.Column('id_tipe', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_tipe', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipe')
    )
    op.create_table('faq',
    sa.Column('id_faq', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_faq')
    )
    op.create_table('gender_baju',
    sa.Column('id_gender', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_gender', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id_gender')
    )
    op.create_table('jenis_outfit',
    sa.Column('id_jenis', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_jenis', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_jenis')
    )
    op.create_table('kategori',
    sa.Column('id_kategori', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('master_category',
    sa.Column('id_master_category', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_master', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_master_category')
    )
    op.create_table('musim',
    sa.Column('id_musim', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_musim', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_musim')
    )
    op.create_table('style',
    sa.Column('id_style', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_style', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_style')
    )
    op.create_table('sub_category',
    sa.Column('id_sub_category', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_sub_category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_sub_category')
    )
    op.create_table('tahun_keluaran',
    sa.Column('id_tahun', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_tahun')
    )
    op.create_table('orderan',
    sa.Column('id_orderan', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_orderan')
    )
    op.create_table('outfit',
    sa.Column('id_outfit', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('id_kategori', sa.BIGINT(), nullable=False),
    sa.Column('id_jenis', sa.BIGINT(), nullable=False),
    sa.Column('id_musim', sa.BIGINT(), nullable=True),
    sa.Column('warna', sa.String(length=100), nullable=False),
    sa.Column('nama_outfit', sa.String(length=100), nullable=False),
    sa.Column('harga_sewa', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Integer(), nullable=False),
    sa.Column('ukuran', sa.String(length=20), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=False),
    sa.Column('detail_produk', sa.String(length=300), nullable=False),
    sa.Column('id_style', sa.BIGINT(), nullable=False),
    sa.Column('is_keranjang', sa.Boolean(), nullable=False),
    sa.Column('is_wishlish', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_jenis'], ['jenis_outfit.id_jenis'], ),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.ForeignKeyConstraint(['id_musim'], ['musim.id_musim'], ),
    sa.ForeignKeyConstraint(['id_style'], ['style.id_style'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_outfit')
    )
    op.create_table('detail_order',
    sa.Column('id_detail', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_orderan', sa.BIGINT(), nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('harga_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_orderan'], ['orderan.id_orderan'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_detail')
    )
    op.create_table('foto_outfit',
    sa.Column('id_foto', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('review',
    sa.Column('id_review', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('ulasan', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tanggal_review', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_review')
    )
    op.create_table('size',
    sa.Column('id_size', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('waist', sa.String(length=6), nullable=False),
    sa.Column('hip', sa.String(length=6), nullable=False),
    sa.Column('length', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.PrimaryKeyConstraint('id_size')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size')
    op.drop_table('review')
    op.drop_table('foto_outfit')
    op.drop_table('detail_order')
    op.drop_table('outfit')
    op.drop_table('orderan')
    op.drop_table('tahun_keluaran')
    op.drop_table('sub_category')
    op.drop_table('style')
    op.drop_table('musim')
    op.drop_table('master_category')
    op.drop_table('kategori')
    op.drop_table('jenis_outfit')
    op.drop_table('gender_baju')
    op.drop_table('faq')
    op.drop_table('article_type')
    # ### end Alembic commands ###
