"""create tb role

Revision ID: 61a67dcd6b87
Revises: 4861d9e58a20
Create Date: 2022-05-31 21:35:02.882302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a67dcd6b87'
down_revision = '4861d9e58a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id_role', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
