"""add outfit FK

Revision ID: a1cb87daf8df
Revises: 3a93cf47e19a
Create Date: 2022-06-03 20:19:07.887389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb87daf8df'
down_revision = '3a93cf47e19a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfit', sa.Column('id_gender', sa.BIGINT(), nullable=True))
    op.add_column('outfit', sa.Column('id_tahun', sa.BIGINT(), nullable=True))
    op.add_column('outfit', sa.Column('id_tipe', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'outfit', 'tahun_keluaran', ['id_tahun'], ['id_tahun'])
    op.create_foreign_key(None, 'outfit', 'article_type', ['id_tipe'], ['id_tipe'])
    op.create_foreign_key(None, 'outfit', 'gender_baju', ['id_gender'], ['id_gender'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outfit', type_='foreignkey')
    op.drop_constraint(None, 'outfit', type_='foreignkey')
    op.drop_constraint(None, 'outfit', type_='foreignkey')
    op.drop_column('outfit', 'id_tipe')
    op.drop_column('outfit', 'id_tahun')
    op.drop_column('outfit', 'id_gender')
    # ### end Alembic commands ###
