"""fix db

Revision ID: c50ab9518b5c
Revises: 
Create Date: 2022-06-05 22:33:43.590698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50ab9518b5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id_faq', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_faq')
    )
    op.create_table('gender_baju',
    sa.Column('id_gender', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_gender', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id_gender')
    )
    op.create_table('kategori',
    sa.Column('id_kategori', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_kategori')
    )
    op.create_table('master_category',
    sa.Column('id_master_category', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_master', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_master_category')
    )
    op.create_table('musim',
    sa.Column('id_musim', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_musim', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_musim')
    )
    op.create_table('role',
    sa.Column('id_role', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('style',
    sa.Column('id_style', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('nama_style', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_style')
    )
    op.create_table('tahun_keluaran',
    sa.Column('id_tahun', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_tahun')
    )
    op.create_table('sub_category',
    sa.Column('id_sub_category', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_master_category', sa.BIGINT(), nullable=False),
    sa.Column('nama_sub_category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_master_category'], ['master_category.id_master_category'], ),
    sa.PrimaryKeyConstraint('id_sub_category')
    )
    op.create_table('user',
    sa.Column('id_user', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_role', sa.BIGINT(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('lokasi', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('no_hp', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('photo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('article_type',
    sa.Column('id_tipe', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_sub_category', sa.BIGINT(), nullable=False),
    sa.Column('nama_tipe', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_sub_category'], ['sub_category.id_sub_category'], ),
    sa.PrimaryKeyConstraint('id_tipe')
    )
    op.create_table('orderan',
    sa.Column('id_orderan', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_orderan')
    )
    op.create_table('detail_order',
    sa.Column('id_detail', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_orderan', sa.BIGINT(), nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('harga_item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_orderan'], ['orderan.id_orderan'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_detail')
    )
    op.create_table('outfit',
    sa.Column('id_outfit', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=False),
    sa.Column('id_kategori', sa.BIGINT(), nullable=False),
    sa.Column('id_gender', sa.BIGINT(), nullable=True),
    sa.Column('id_tahun', sa.BIGINT(), nullable=True),
    sa.Column('id_musim', sa.BIGINT(), nullable=True),
    sa.Column('id_tipe', sa.BIGINT(), nullable=True),
    sa.Column('warna', sa.String(length=150), nullable=False),
    sa.Column('nama_outfit', sa.String(length=100), nullable=False),
    sa.Column('harga_sewa', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(length=500), nullable=False),
    sa.Column('detail_produk', sa.String(length=300), nullable=False),
    sa.Column('id_style', sa.BIGINT(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_gender'], ['gender_baju.id_gender'], ),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id_kategori'], ),
    sa.ForeignKeyConstraint(['id_musim'], ['musim.id_musim'], ),
    sa.ForeignKeyConstraint(['id_style'], ['style.id_style'], ),
    sa.ForeignKeyConstraint(['id_tahun'], ['tahun_keluaran.id_tahun'], ),
    sa.ForeignKeyConstraint(['id_tipe'], ['article_type.id_tipe'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_outfit')
    )
    op.create_table('foto_outfit',
    sa.Column('id_foto', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_table('review',
    sa.Column('id_review', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BIGINT(), nullable=True),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('ulasan', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('tanggal_review', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_review')
    )
    op.create_table('size',
    sa.Column('id_size', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_outfit', sa.BIGINT(), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('waist', sa.String(length=6), nullable=False),
    sa.Column('hip', sa.String(length=6), nullable=False),
    sa.Column('length', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['id_outfit'], ['outfit.id_outfit'], ),
    sa.PrimaryKeyConstraint('id_size')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('size')
    op.drop_table('review')
    op.drop_table('foto_outfit')
    op.drop_table('outfit')
    op.drop_table('detail_order')
    op.drop_table('orderan')
    op.drop_table('article_type')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('sub_category')
    op.drop_table('tahun_keluaran')
    op.drop_table('style')
    op.drop_table('role')
    op.drop_table('musim')
    op.drop_table('master_category')
    op.drop_table('kategori')
    op.drop_table('gender_baju')
    op.drop_table('faq')
    # ### end Alembic commands ###
