"""adding relationship

Revision ID: d20cd12e9640
Revises: 61a67dcd6b87
Create Date: 2022-05-31 21:47:08.890945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd20cd12e9640'
down_revision = '61a67dcd6b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_role', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
