"""adding relationship

Revision ID: f4fca5446f98
Revises: d20cd12e9640
Create Date: 2022-05-31 21:56:56.834146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fca5446f98'
down_revision = 'd20cd12e9640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_role', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['id_role'], ['id_role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'id_role')
    # ### end Alembic commands ###
