"""fix db

Revision ID: fdc090e6b38d
Revises: a1cb87daf8df
Create Date: 2022-06-03 20:19:54.353409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc090e6b38d'
down_revision = 'a1cb87daf8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_type', sa.Column('id_sub_category', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'article_type', 'sub_category', ['id_sub_category'], ['id_sub_category'])
    op.add_column('sub_category', sa.Column('id_master_category', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'sub_category', 'master_category', ['id_master_category'], ['id_master_category'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_category', type_='foreignkey')
    op.drop_column('sub_category', 'id_master_category')
    op.drop_constraint(None, 'article_type', type_='foreignkey')
    op.drop_column('article_type', 'id_sub_category')
    # ### end Alembic commands ###
